### ISSUE TITLE
Logging for the Modular Alert action

### ISSUE THREAD

**Issue by archspangler** [puppetlabs/TA-puppet-report-viewer#14]
I can see in Splunk where my Modular Alert action is being fired, however I never see a Detailed report pulled back.  I have verified my Puppet Token\user access is all correct.   

I am having trouble finding where the TA Puppet-report-viewer Modular Alert action is being logged.  Furthermore, do you know what Puppet Server log I can look at to see if Splunk is attempting to pull the detailed report from the Puppet Server?

-Archie

**Comment by mrzarquon** [comment]
We've added https://github.com/puppetlabs/TA-puppet-report-viewer#troubleshooting-and-verification

Was this able to help you sort out where to look for logs / troubleshoot the actions?

**Comment by archspangler** [comment]
My issue was that the HEC endpoint was assumed to be HTTPS and ours is HTTP.   I didn't see any errors logged anywhere about this connection failure to HEC.

**Comment by mrzarquon** [comment]
Ah, ok - I will close out this issue as it's addressed in PIE-99 / Issue #17
