### ISSUE TITLE
http for detailed reports / multiple Puppet masters

### ISSUE THREAD

**Issue by archspangler** [puppetlabs/TA-puppet-report-viewer#17]
Couple of questions:

1.  How would one go about using http for forwarding detailed event to HEC?  I see it's hard coded for https in the modalert_generate_detailed_report_helper.py file.

2.  How would one go about configuring for 2 or more Puppet masters in the ta_puppet_report_viewer_settings.conf?   

[additional_parameters]
puppet_db_server = 
auth_token = ********
splunk_server = 
splunk_hec_token = ********
pe_console = 

-Archie

**Comment by mrzarquon** [comment]
1) We will be adding better URI handling in a new release, so you'd provide us with the full URL to the collector end point (https://splunk:8088/services/collector) and we'll switch there vs hard coded ssl assumption.

2) Do you mean multiple PE consoles (as in fully separate puppet enterprise installs) or just multiple puppet masters sharing one PuppetDB/Console (ie compile masters)? 

We don't yet have support for adding configuration data for second puppetdb hostname/credential, but if you're in the latter scenario, the PE auth token and credentials for that one puppetdb server is all you need.

**Comment by mrzarquon** [comment]
We're tracking this work here:

http for hec - https://tickets.puppetlabs.com/browse/PIE-99

multiple pe installs - https://tickets.puppetlabs.com/browse/PIE-98

**Comment by archspangler** [comment]
Thanks for the update Chris!

**Comment by mrzarquon** [comment]
Latest revision in master as of writing this now supports http URIs (we switch to you providing full URLs, so if you give us http:// vs https:// it is handled automatically).

We're investigating how to do the UI changes for multiple PE installs right now for the actions

**Comment by mrzarquon** [comment]
HTTP support is in the 2.0.0 release.
Will be adding an overrides parameter that will allow you to specific a different PE server to use for any alert action (assumes you're using the same username/password for the PE server in question - assuming one uses ldap / ad user account)

**Comment by mrzarquon** [comment]
We've added support for a per alert "override" that lets you set a different puppetserver for the alert you want to perform the search on, however we do require you to use the same username/password in each PE install it is running the alert against right now.

**Comment by coreymbe** [comment]
Closing this issue out as it has since been resolved.
