### ISSUE TITLE
TA-puppet-report-viewer add-on configuration page access issue 

### ISSUE THREAD

**Issue by vijayadhandapani** [puppetlabs/TA-puppet-report-viewer#23]
Hi There,

I have installed Puppet report viewer add-on in my Splunk Search Head in production environment. But when I tried to access configuration page, it keeps loading as shown in screenshot attached. 

Please assist.

Thank you.

![puppet_config](https://user-images.githubusercontent.com/48018674/62364832-2da78b00-b540-11e9-803a-2c073067849f.png)

**Comment by mrzarquon** [comment]
What is your splunk version?

**Comment by vijayadhandapani** [comment]
Hi,

I have installed Puppet report viewer version 2.0.0 Build 3 on test Splunk version 7.2.6.

As mentioned in following link https://github.com/puppetlabs/TA-puppet-report-viewer, configuration page is not same, it did not ask for Puppet token anywhere, also it does not have Puppet DB server information as shown in attached snapshot.
![test_Splunk_Puppet_addon](https://user-images.githubusercontent.com/48018674/65043481-a0e25080-d978-11e9-9087-88593de47b96.png)

is the information given in github link is wrong, or am I missing something? Please assist.

**Comment by mrzarquon** [comment]
We're updating documentation now to reflect the new settings / values for 2.0
