### ISSUE TITLE
Puppet Report Viewer add-on configuration page is missing Puppet token information?

### ISSUE THREAD

**Issue by vijayadhandapani** [puppetlabs/TA-puppet-report-viewer#34]
Hi,

I have installed Puppet report viewer version 2.0.0 Build 3 on test Splunk version 7.2.6.
As mentioned in following link https://github.com/puppetlabs/TA-puppet-report-viewer, configuration page is not same, it did not ask for Puppet token anywhere, also it does not have Puppet DB server information as shown in attached snapshot.

![test_Splunk_Puppet_addon](https://user-images.githubusercontent.com/48018674/65044047-cf146000-d979-11e9-8939-63afc5586d83.png)

Is instructions given in github portal wrong, or am I missing something? Please assist.

**Comment by mrzarquon** [comment]
The instructions need to be updated, you just need to provide the username and password for the user in Puppet Enterprise that would have generated a token. You do not need to provide the PuppetDB information unless you know your PE installation has PuppetDB on a different server than the console (in most installations, it is not).

**Comment by vijayadhandapani** [comment]
Thanks for the update. Yes I did what you have suggested. I have also created four HEC tokens. We have also updated Puppet Splunk HEC module at test Puppet server. 

I am sending all Puppet logs to index=main in test Splunk and updated all information as mentioned in https://github.com/puppetlabs/TA-puppet-report-viewer. When I searched with index=main and sourcetype=puppet:* I can see data only from Puppet:summary sourcetype as shown in attachment, rest all (detailed, facts, metrics) are missing. 
![Test_Puppet_logs](https://user-images.githubusercontent.com/48018674/65120021-a1c3c280-da0a-11e9-83e2-105fbdbdb827.png)

As mentioned in github instructions, Report Builder dashbaord does not show any output (refer snapshot)
![Report_Builder](https://user-images.githubusercontent.com/48018674/65120335-1696fc80-da0b-11e9-8b5d-9a0189f09d51.png)

Could you please let me know how can I confirm Puppet add-on is working as expected? Please assist.

**Comment by vijayadhandapani** [comment]
We have completed all steps mentioned in github portal, we are still not seeing facts and metrics data. Can someone pelase let me know what is the issue here in accessing these logs from test Puppet machine? how can I fix this?

**Comment by mrzarquon** [comment]
Have you configured the splunk_hec module to manage_routes and enable_reports on your Puppet Enterprise installation? Steps for facts to show would be here:

https://forge.puppet.com/puppetlabs/splunk_hec#fact-terminus-support

If you have further questions, reach to your Puppet support contact and we can better handle that through that mechanism.

**Comment by vijayadhandapani** [comment]
Thanks for your response.
